//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Game
{
	public int numTrials;
	public int numCols;
	public int numRows;
	public int numBlacks;
	public int numCorrect;
	public int numIncorrect;
	public int gameLevel;
	public int gameScore;

	public Game ()
	{

	}
}