//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public class GameTile
{
	public enum CellState{
		WhiteHidden,
		BlackHidden,
		WhiteShown,
		BlackShown,
	}


	public int locX {get; private set;}
	public int locY {get; private set;}

	public CellState cellState;
	public GameObject Go;


	public GameTile (GameObject tile, int x, int y)
	{
		Go = tile;
		cellState = CellState.WhiteHidden;
		locX = x;
		locY = y;
	}
}

